export const MESSAGE_SENT = "MESSAGE_SENT";
export const MESSAGE_LOG_LOADED = "MESSAGE_LOG_LOADED";
export const MESSAGE_LOG_EMPTY = "MESSAGELOG_EMPTY";
export const EMOJI_TOGGLED = "EMOJI_TOGGLED";
export const EMOJI_CLOSED = "EMOJI_CLOSED";
export const EMOJI_SENT = "EMOJI_SENT";
export const MESSAGE_URL_LOADED = "MESSAGE_URL_LOADED";
