export const MESSAGE_SENT = "MESSAGE_SENT";
export const MESSAGE_LOG_LOADED = "MESSAGE_LOG_LOADED";
export const MESSAGE_LOG_EMPTY = "MESSAGELOG_EMPTY";
export const LOADING_STARTED = 'LOADING_STARTED';
export const LOADING_STOPPED = 'LOADING_STOPPED';
